apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
    {{- include "vaultwarden.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.statefulsetlabels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
spec:
  serviceName: vaultwarden
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: vaultwarden
      {{- include "vaultwarden.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: vaultwarden
        {{- include "vaultwarden.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha1sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha1sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: {{ .Values.runAsUser }}
        runAsGroup: {{ .Values.runAsUser }}
        fsGroup: {{ .Values.runAsUser }}
      initContainers:
        {{- if .Values.initContainers }}
        {{- toYaml .Values.initContainers | nindent 8 }}
        {{- end }}
        # Copy rclone config from read-only secret mount to writable share
        # https://github.com/rclone/rclone/issues/3655
        - name: copy-config
          image: busybox:latest
          command: ["sh", "-c", "cp -v /src-config/rclone.conf /config/"]
          volumeMounts:
            - name: backup-secret-conf
              mountPath: "/src-config/"
              readOnly: true
            - name: config
              mountPath: "/config/"
      containers:
        - image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: vaultwarden
          securityContext:
            allowPrivilegeEscalation: false
          envFrom:
            - configMapRef:
                name: {{ include "vaultwarden.fullname" . }}
          env:
            {{- if or (.Values.smtp.username.value) (.Values.smtp.username.existingSecretKey )}}
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "vaultwarden.fullname" .) .Values.smtp.existingSecret }}
                  key: {{ default "SMTP_USERNAME" .Values.smtp.username.existingSecretKey }}
            {{- end }}
            {{- if or (.Values.smtp.password.value) (.Values.smtp.password.existingSecretKey )}}
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "vaultwarden.fullname" .) .Values.smtp.existingSecret }}
                  key: {{ default "SMTP_PASSWORD" .Values.smtp.password.existingSecretKey }}
            {{- end }}
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "vaultwarden.fullname" .) .Values.adminToken.existingSecret }}
                  key: {{ default "ADMIN_TOKEN" .Values.adminToken.existingSecretKey }}
            {{- if ne "default" .Values.database.type }}
            - name: DATABASE_URL
              {{- if .Values.database.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: {{ .Values.database.existingSecretKey }}
              {{- else }}
              {{- if .Values.database.uriOverride }}
              value: {{ .Values.database.uriOverride }}
              {{- else }}
              value: {{ include "dbString" . | quote }}
              {{- end }}
              {{- end }}
            {{- end }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: {{ .Values.websocket.port }}
              name: websocket
              protocol: TCP
          {{- if .Values.storage.enabled }}
          volumeMounts:
            - name: vaultwarden-data
              mountPath: {{ .Values.storage.dataDir }}
          {{- end }}
          resources:
            limits:
              cpu: 300m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
        {{- if and .Values.backup .Values.storage.enabled }}
        {{- range .Values.backup.backups }}
        - image: {{ $.Values.backup.image }}
          name: backup-{{ .name }}
{{/*          command: ["sh", "-c", "sleep 100000"]*/}}
          securityContext:
            allowPrivilegeEscalation: false

          env:
            - name: DATA_DIR
              value: {{ $.Values.storage.dataDir | quote }}
            - name: RCLONE_REMOTE_NAME
              value: {{ $.Values.backup.remoteName | quote }}
            - name: RCLONE_REMOTE_DIR
              value: {{ .remoteDir | quote }}
            - name: RCLONE_GLOBAL_FLAG
              value: "{{ $.Values.backup.globalFlags }} --config /config/rclone.conf"
            - name: CRON
              value: {{ .cron | quote }}
            - name: ZIP_PASSWORD
              value: {{ $.Values.backup.zipPassword | quote }}
            - name: BACKUP_KEEP_DAYS
              value: {{ .keepDays | quote }}
            - name: BACKUP_FILE_DATE_SUFFIX
              value: {{ .fileDateSuffix | quote }}
            - name: TIMEZONE
              value: {{ $.Values.backup.timezone | quote }}
            {{- if .healthCheckPing }}
            - name: PING_URL
              value: {{ (tpl .healthCheckPing  $) | quote }}
            {{- end }}
            {{- if $.Values.backup.smtp.enabled }}
            - name: MAIL_SMTP_ENABLE
              value: "true"
            - name: MAIL_SMTP_VARIABLES
              value: {{ $.Values.backup.smtp.smtpVariables | quote }}
            - name: MAIL_TO
              value: {{ $.Values.backup.smtp.mailTo | quote }}
            - name: MAIL_WHEN_SUCCESS
              value: {{ $.Values.backup.smtp.mailWhenSuccess | quote }}
            - name: MAIL_WHEN_FAILURE
              value: {{ $.Values.backup.smtp.mailWhenFailure | quote }}
            {{- end }}
            # When run as non-root, script cannot create crontabs in home folcer
          volumeMounts:
            - name: vaultwarden-data
              mountPath: {{ $.Values.storage.dataDir }}
            - name: config
              mountPath: "/config/"
        {{- end }}
        {{- end }}
        {{- if .Values.sidecars }}
        {{- toYaml .Values.sidecars | nindent 8 }}
        {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      volumes:
        - name: backup-secret-conf
          secret:
            secretName: {{ include "vaultwarden.fullname" . }}-rclone
            optional: false
            # readable by user/owner
            defaultMode: 0400
        - name: config
          emptyDir: {}

  {{- if .Values.storage.enabled }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  volumeClaimTemplates:
    - metadata:
        name: vaultwarden-data
        labels:
          {{- include "vaultwarden.labels" . | nindent 10 }}
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.storage.size }}
        storageClassName: {{ default "default" .Values.storage.class }}
  {{- end }}
